#!/usr/bin/env python3
"""Create permitted Developer Associate source-question metadata."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


DEVELOPER_CERTIFICATION = "AWS Certified Developer"
DEVELOPER_EXAM_CODE = "DVA-C02"


SOURCE_ROWS = [
    {
        "source_id": "dva-lambda-sqs-dlq",
        "source_name": "AWS Documentation: Lambda with SQS event sources",
        "source_url": "https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Select an event-driven processing pattern that retries failed queue messages and isolates poison messages.",
        "services": ["AWS Lambda", "Amazon SQS"],
        "concepts": ["Lambda event source mapping", "SQS queue", "dead-letter queue", "failed message retry"],
        "difficulty": "Medium",
        "exam_style_notes": "Troubleshooting scenario with an event source, retry behavior, and failure isolation distractors.",
        "distractor_pattern": "Confuse Lambda async destinations, SNS fanout, and CloudWatch alarms with queue failure handling.",
        "reasoning_pattern": "Choose the configuration that preserves messages while preventing repeated failures from blocking processing.",
    },
    {
        "source_id": "dva-api-gateway-lambda-auth",
        "source_name": "AWS Documentation: API Gateway Lambda authorizers",
        "source_url": "https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Security",
        "task_statement": "Secure an API by running custom authorization logic before a backend Lambda integration is invoked.",
        "services": ["Amazon API Gateway", "AWS Lambda"],
        "concepts": ["API Gateway", "Lambda authorizer", "custom authorization", "backend integration"],
        "difficulty": "Medium",
        "exam_style_notes": "Security configuration scenario asking for the best API access-control mechanism.",
        "distractor_pattern": "Contrast authorizers with WAF rules, security groups, and IAM roles for compute.",
        "reasoning_pattern": "Identify request-time authorization at the API boundary rather than network or instance controls.",
    },
    {
        "source_id": "dva-dynamodb-conditional-write",
        "source_name": "AWS Documentation: DynamoDB condition expressions",
        "source_url": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Prevent overwriting an item when concurrent writers try to create the same DynamoDB record.",
        "services": ["Amazon DynamoDB"],
        "concepts": ["DynamoDB", "condition expression", "conditional write", "concurrent writes"],
        "difficulty": "Medium",
        "exam_style_notes": "Data consistency scenario requiring a service feature rather than application-side locking.",
        "distractor_pattern": "Confuse conditional writes with scans, global tables, and provisioned throughput changes.",
        "reasoning_pattern": "Use an atomic write condition to enforce uniqueness at the table operation.",
    },
    {
        "source_id": "dva-codepipeline-codebuild",
        "source_name": "AWS Documentation: CodePipeline with CodeBuild",
        "source_url": "https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodeBuild.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Deployment",
        "task_statement": "Run repeatable build and test commands as part of an automated application release pipeline.",
        "services": ["AWS CodePipeline", "AWS CodeBuild"],
        "concepts": ["CodePipeline", "CodeBuild", "build stage", "automated release"],
        "difficulty": "Medium",
        "exam_style_notes": "CI/CD workflow scenario with build automation and deployment-stage distractors.",
        "distractor_pattern": "Contrast build actions with CodeDeploy traffic shifting, CloudFormation stacks, and manual scripts.",
        "reasoning_pattern": "Choose the managed build action that integrates into a deployment pipeline.",
    },
    {
        "source_id": "dva-xray-tracing",
        "source_name": "AWS Documentation: AWS X-Ray tracing",
        "source_url": "https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Troubleshooting and Optimization",
        "task_statement": "Trace requests across distributed application components to find latency and downstream errors.",
        "services": ["AWS X-Ray"],
        "concepts": ["X-Ray", "distributed tracing", "service map", "latency troubleshooting"],
        "difficulty": "Medium",
        "exam_style_notes": "Observability troubleshooting scenario asking for request-level tracing rather than metrics alone.",
        "distractor_pattern": "Distinguish tracing from CloudWatch metrics, CloudTrail audit logs, and Config history.",
        "reasoning_pattern": "Select tracing to follow a request path across services and diagnose latency.",
    },
    {
        "source_id": "dva-lambda-env-vars",
        "source_name": "AWS Documentation: Lambda environment variables",
        "source_url": "https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Configure a Lambda function with non-secret settings that can vary between deployment environments.",
        "services": ["AWS Lambda"],
        "concepts": ["Lambda environment variables", "function configuration", "deployment environment", "non-secret settings"],
        "difficulty": "Medium",
        "exam_style_notes": "Configuration scenario asking where to store runtime settings for a serverless function.",
        "distractor_pattern": "Distinguish environment variables from Secrets Manager, IAM roles, and CloudWatch Logs.",
        "reasoning_pattern": "Use function environment configuration for non-sensitive values that differ by stage.",
    },
    {
        "source_id": "dva-secrets-manager-rotation",
        "source_name": "AWS Documentation: Secrets Manager rotation",
        "source_url": "https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Security",
        "task_statement": "Store database credentials for an application and rotate them automatically on a schedule.",
        "services": ["AWS Secrets Manager"],
        "concepts": ["Secrets Manager", "secret rotation", "database credentials", "scheduled rotation"],
        "difficulty": "Medium",
        "exam_style_notes": "Security scenario requiring managed secret storage and automatic credential rotation.",
        "distractor_pattern": "Contrast secret rotation with Lambda environment variables, KMS keys alone, and Parameter Store without rotation.",
        "reasoning_pattern": "Select the managed secrets service that can invoke rotation workflows for credentials.",
    },
    {
        "source_id": "dva-sqs-visibility-timeout",
        "source_name": "AWS Documentation: SQS visibility timeout",
        "source_url": "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Prevent other consumers from immediately receiving an SQS message while one worker is still processing it.",
        "services": ["Amazon SQS"],
        "concepts": ["SQS visibility timeout", "message processing", "queue consumers", "duplicate delivery control"],
        "difficulty": "Medium",
        "exam_style_notes": "Message-processing scenario focused on queue visibility during long-running work.",
        "distractor_pattern": "Confuse visibility timeout with delay queues, retention periods, and dead-letter queues.",
        "reasoning_pattern": "Adjust the queue visibility window so in-flight messages stay hidden long enough to finish processing.",
    },
    {
        "source_id": "dva-dynamodb-streams-lambda",
        "source_name": "AWS Documentation: Lambda with DynamoDB Streams",
        "source_url": "https://docs.aws.amazon.com/lambda/latest/dg/with-ddb.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Invoke application code when items in a DynamoDB table are inserted, updated, or deleted.",
        "services": ["Amazon DynamoDB", "AWS Lambda"],
        "concepts": ["DynamoDB Streams", "Lambda event source mapping", "table item changes", "event-driven processing"],
        "difficulty": "Medium",
        "exam_style_notes": "Event-driven data scenario asking how to react to table mutations.",
        "distractor_pattern": "Distinguish DynamoDB Streams from scans, CloudTrail events, and scheduled polling.",
        "reasoning_pattern": "Enable the stream and connect it to Lambda so record changes trigger processing.",
    },
    {
        "source_id": "dva-api-gateway-throttling",
        "source_name": "AWS Documentation: API Gateway throttling",
        "source_url": "https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Security",
        "task_statement": "Limit the request rate for clients calling a public API to protect backend integrations.",
        "services": ["Amazon API Gateway"],
        "concepts": ["API Gateway throttling", "rate limits", "burst limits", "backend protection"],
        "difficulty": "Medium",
        "exam_style_notes": "API protection scenario asking for request-rate controls at the API edge.",
        "distractor_pattern": "Contrast throttling with Lambda reserved concurrency, WAF rules, and CloudWatch alarms.",
        "reasoning_pattern": "Configure throttling limits where the API receives client traffic before invoking the backend.",
    },
    {
        "source_id": "dva-codebuild-buildspec",
        "source_name": "AWS Documentation: CodeBuild buildspec reference",
        "source_url": "https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Deployment",
        "task_statement": "Define repeatable install, build, and test commands for a managed build project.",
        "services": ["AWS CodeBuild"],
        "concepts": ["CodeBuild buildspec", "build phases", "test commands", "managed build project"],
        "difficulty": "Medium",
        "exam_style_notes": "CI build configuration scenario asking where command phases should be declared.",
        "distractor_pattern": "Distinguish buildspec files from CodeDeploy AppSpec files, IAM policies, and CloudFormation parameters.",
        "reasoning_pattern": "Place repeatable build commands in the CodeBuild buildspec so the managed build can execute them.",
    },
    {
        "source_id": "dva-eventbridge-schedule-lambda",
        "source_name": "AWS Documentation: EventBridge scheduled rules",
        "source_url": "https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-run-lambda-schedule.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Run a Lambda function on a recurring schedule without provisioning a server.",
        "services": ["Amazon EventBridge", "AWS Lambda"],
        "concepts": ["EventBridge scheduled rule", "Lambda target", "recurring schedule", "serverless automation"],
        "difficulty": "Medium",
        "exam_style_notes": "Serverless automation scenario asking how to trigger periodic work.",
        "distractor_pattern": "Contrast scheduled rules with SQS queues, CloudTrail events, and manual invocations.",
        "reasoning_pattern": "Create a schedule rule that targets the Lambda function for recurring execution.",
    },
    {
        "source_id": "dva-lambda-reserved-concurrency",
        "source_name": "AWS Documentation: Lambda reserved concurrency",
        "source_url": "https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Troubleshooting and Optimization",
        "task_statement": "Limit how many concurrent executions a Lambda function can consume while reserving capacity for it.",
        "services": ["AWS Lambda"],
        "concepts": ["Lambda reserved concurrency", "concurrent executions", "capacity reservation", "throttling control"],
        "difficulty": "Medium",
        "exam_style_notes": "Operational control scenario where a function must be capped without changing application code.",
        "distractor_pattern": "Distinguish reserved concurrency from provisioned concurrency, memory settings, and API Gateway throttling.",
        "reasoning_pattern": "Choose the Lambda setting that both reserves and limits concurrency for one function.",
        "generated_question": "A production Lambda function can overwhelm a downstream database during traffic spikes, but the team also wants guaranteed capacity for that function. Which Lambda setting should the developer configure?",
        "correct_option": "Configure Lambda reserved concurrency.",
        "reference_answer": "Configure Lambda reserved concurrency to reserve capacity for the function and cap its concurrent executions to protect downstream systems.",
        "distractors": ["Configure Lambda provisioned concurrency only.", "Increase the function memory size.", "Add an API Gateway usage plan only."],
    },
    {
        "source_id": "dva-lambda-async-destination",
        "source_name": "AWS Documentation: Lambda asynchronous invocation destinations",
        "source_url": "https://docs.aws.amazon.com/lambda/latest/dg/invocation-async-retain-records.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Route records from asynchronous Lambda invocations to another service after success or failure.",
        "services": ["AWS Lambda"],
        "concepts": ["Lambda destinations", "asynchronous invocation", "success destination", "failure destination"],
        "difficulty": "Medium",
        "exam_style_notes": "Event handling scenario asking how to capture async invocation outcomes without polling logs.",
        "distractor_pattern": "Contrast async destinations with DLQs, synchronous responses, and CloudWatch dashboards.",
        "reasoning_pattern": "Configure destinations on the Lambda async invocation path to send outcome records to supported targets.",
        "generated_question": "An asynchronously invoked Lambda function must send successful results to one target and failed invocation records to another target for follow-up processing. Which feature should the developer use?",
        "correct_option": "Configure Lambda destinations.",
        "reference_answer": "Configure Lambda destinations for asynchronous invocations so success and failure records are routed to the appropriate targets.",
        "distractors": ["Enable Lambda provisioned concurrency.", "Create a CloudWatch metric alarm only.", "Return a custom HTTP response from the function."],
    },
    {
        "source_id": "dva-api-gateway-canary-release",
        "source_name": "AWS Documentation: API Gateway canary release deployments",
        "source_url": "https://docs.aws.amazon.com/apigateway/latest/developerguide/canary-release.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Deployment",
        "task_statement": "Send a small percentage of API Gateway stage traffic to a new deployment before full rollout.",
        "services": ["Amazon API Gateway"],
        "concepts": ["API Gateway canary release", "stage traffic", "deployment", "percentage rollout"],
        "difficulty": "Medium",
        "exam_style_notes": "Deployment safety scenario where only part of API traffic should reach the new version.",
        "distractor_pattern": "Contrast canary settings with Lambda aliases, CloudFront cache behaviors, and DNS weighted records.",
        "reasoning_pattern": "Use API Gateway stage canary settings to route a controlled percentage of requests to the new deployment.",
        "generated_question": "A REST API release should expose a new deployment to 10 percent of callers while most clients continue using the current API stage. Which API Gateway deployment feature fits this rollout?",
        "correct_option": "Use an API Gateway canary release.",
        "reference_answer": "Use an API Gateway canary release on the stage to send a configured percentage of traffic to the new deployment.",
        "distractors": ["Configure an SQS FIFO queue.", "Increase the Lambda timeout.", "Create a CloudWatch Logs metric filter only."],
    },
    {
        "source_id": "dva-api-gateway-usage-plan-api-key",
        "source_name": "AWS Documentation: API Gateway usage plans and API keys",
        "source_url": "https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-usage-plans.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Security",
        "task_statement": "Apply quota and throttling limits to identified API clients by using API keys.",
        "services": ["Amazon API Gateway"],
        "concepts": ["API Gateway usage plan", "API key", "quota", "throttling"],
        "difficulty": "Medium",
        "exam_style_notes": "Client access-control scenario focused on per-client request quotas rather than authorization.",
        "distractor_pattern": "Distinguish usage plans from Lambda authorizers, WAF rules, and IAM execution roles.",
        "reasoning_pattern": "Associate API keys with usage plans to enforce quotas and rate limits for client applications.",
        "generated_question": "A partner-facing API needs different request quotas for each client application, and callers will include API keys. Which API Gateway configuration should the developer create?",
        "correct_option": "Create an API Gateway usage plan with API keys.",
        "reference_answer": "Create an API Gateway usage plan, associate API keys with it, and configure quota and throttling limits for those clients.",
        "distractors": ["Create a Lambda layer.", "Enable DynamoDB TTL.", "Configure an S3 bucket policy only."],
    },
    {
        "source_id": "dva-dynamodb-ttl",
        "source_name": "AWS Documentation: DynamoDB Time to Live",
        "source_url": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Automatically delete expired DynamoDB items based on an epoch timestamp attribute.",
        "services": ["Amazon DynamoDB"],
        "concepts": ["DynamoDB TTL", "expiration timestamp", "automatic deletion", "table items"],
        "difficulty": "Medium",
        "exam_style_notes": "Data lifecycle scenario asking for a native table feature instead of scheduled scans.",
        "distractor_pattern": "Contrast TTL with lifecycle policies, table scans, and backup retention.",
        "reasoning_pattern": "Enable TTL on the timestamp attribute so DynamoDB removes expired items asynchronously.",
        "generated_question": "A session table in DynamoDB stores an expiration time for each item and should remove old sessions without a scheduled cleanup job. Which feature should the developer enable?",
        "correct_option": "Enable DynamoDB Time to Live.",
        "reference_answer": "Enable DynamoDB TTL on the expiration timestamp attribute so DynamoDB automatically deletes expired table items.",
        "distractors": ["Configure S3 Lifecycle rules.", "Run a full table scan from EventBridge.", "Increase read capacity units."],
    },
    {
        "source_id": "dva-dynamodb-transact-write",
        "source_name": "AWS Documentation: DynamoDB transactions",
        "source_url": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transactions.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Update multiple DynamoDB items atomically so all changes succeed or all are canceled.",
        "services": ["Amazon DynamoDB"],
        "concepts": ["DynamoDB transactions", "TransactWriteItems", "atomic update", "all-or-nothing"],
        "difficulty": "Medium",
        "exam_style_notes": "Data consistency scenario where multiple table writes must be committed together.",
        "distractor_pattern": "Confuse transactions with batch writes, streams, and conditional writes for a single item.",
        "reasoning_pattern": "Use DynamoDB transactional APIs when multiple operations must succeed or fail as one unit.",
        "generated_question": "An order workflow must update an inventory item and create an order item in DynamoDB, and either both writes must succeed or neither should be saved. Which DynamoDB API pattern should the developer use?",
        "correct_option": "Use DynamoDB TransactWriteItems.",
        "reference_answer": "Use DynamoDB transactions with TransactWriteItems to perform atomic all-or-nothing updates across the required items.",
        "distractors": ["Use BatchWriteItem without conditions.", "Enable DynamoDB Streams only.", "Increase table write capacity."],
    },
    {
        "source_id": "dva-dynamodb-query-index",
        "source_name": "AWS Documentation: DynamoDB secondary indexes",
        "source_url": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SecondaryIndexes.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Support efficient DynamoDB queries with an alternate partition key without scanning the table.",
        "services": ["Amazon DynamoDB"],
        "concepts": ["DynamoDB secondary index", "alternate partition key", "Query operation", "avoid scans"],
        "difficulty": "Medium",
        "exam_style_notes": "Performance scenario asking for the data modeling feature that supports a new access pattern.",
        "distractor_pattern": "Contrast secondary indexes with scans, backups, streams, and capacity increases.",
        "reasoning_pattern": "Add an index that matches the query access pattern so the application can use Query efficiently.",
        "generated_question": "A DynamoDB table is keyed by customer ID, but the application now needs fast lookups by order status without scanning every item. What should the developer add to support this access pattern?",
        "correct_option": "Add a DynamoDB secondary index.",
        "reference_answer": "Add a DynamoDB secondary index with the alternate partition key so the application can use efficient Query operations and avoid table scans.",
        "distractors": ["Enable point-in-time recovery.", "Increase Lambda memory.", "Create a CloudTrail trail."],
    },
    {
        "source_id": "dva-sqs-fifo-deduplication",
        "source_name": "AWS Documentation: Amazon SQS FIFO queues",
        "source_url": "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Process SQS messages in order and avoid duplicate processing within the deduplication interval.",
        "services": ["Amazon SQS"],
        "concepts": ["SQS FIFO queue", "message ordering", "deduplication", "message group ID"],
        "difficulty": "Medium",
        "exam_style_notes": "Messaging scenario where order and deduplication are both explicit requirements.",
        "distractor_pattern": "Distinguish FIFO queues from standard queues, SNS topics, and visibility timeouts.",
        "reasoning_pattern": "Choose FIFO queue semantics and provide message group and deduplication IDs where needed.",
        "generated_question": "A payment workflow uses SQS and must preserve message order for each account while reducing duplicate processing attempts. Which queue type and message metadata should the developer use?",
        "correct_option": "Use an SQS FIFO queue with message group and deduplication IDs.",
        "reference_answer": "Use an SQS FIFO queue with message group IDs for ordering and deduplication IDs to reduce duplicate processing within the deduplication interval.",
        "distractors": ["Use a standard SQS queue with no grouping.", "Configure an SNS fanout topic only.", "Shorten the queue retention period."],
    },
    {
        "source_id": "dva-sns-filter-policy",
        "source_name": "AWS Documentation: Amazon SNS subscription filter policies",
        "source_url": "https://docs.aws.amazon.com/sns/latest/dg/sns-subscription-filter-policies.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Deliver only matching SNS messages to subscribers based on message attributes.",
        "services": ["Amazon SNS"],
        "concepts": ["SNS filter policy", "message attributes", "subscription filtering", "fanout"],
        "difficulty": "Medium",
        "exam_style_notes": "Event fanout scenario asking how subscribers can receive only relevant messages.",
        "distractor_pattern": "Contrast filter policies with SQS polling code, Lambda aliases, and EventBridge schedules.",
        "reasoning_pattern": "Apply subscription filter policies so SNS routes messages by attributes before delivery.",
        "generated_question": "An SNS topic publishes all order events, but each subscribed queue should receive only messages for selected order types based on attributes. Which SNS feature should the developer configure?",
        "correct_option": "Configure SNS subscription filter policies.",
        "reference_answer": "Configure SNS subscription filter policies that match message attributes so each subscriber receives only the relevant fanout messages.",
        "distractors": ["Configure Lambda reserved concurrency.", "Enable S3 versioning.", "Use an SQS delay queue only."],
    },
    {
        "source_id": "dva-s3-presigned-url",
        "source_name": "AWS Documentation: Sharing objects with presigned URLs",
        "source_url": "https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Security",
        "task_statement": "Grant temporary access to a private S3 object without making the bucket public.",
        "services": ["Amazon S3"],
        "concepts": ["S3 presigned URL", "temporary access", "private object", "expiration"],
        "difficulty": "Medium",
        "exam_style_notes": "Secure access scenario requiring temporary object-level access.",
        "distractor_pattern": "Contrast presigned URLs with public bucket policies, ACLs, and CloudFront invalidations.",
        "reasoning_pattern": "Generate a presigned URL with an expiration so private object access is time limited.",
        "generated_question": "A web application must let an authenticated user download one private S3 object for a limited time without changing the bucket to public access. What should the developer generate?",
        "correct_option": "Generate an S3 presigned URL.",
        "reference_answer": "Generate an S3 presigned URL with an expiration to provide temporary access to the private object without making the bucket public.",
        "distractors": ["Disable S3 Block Public Access.", "Create a public-read bucket ACL.", "Use DynamoDB TTL."],
    },
    {
        "source_id": "dva-s3-multipart-upload",
        "source_name": "AWS Documentation: Multipart upload overview",
        "source_url": "https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Upload large S3 objects in parts and retry failed parts independently.",
        "services": ["Amazon S3"],
        "concepts": ["S3 multipart upload", "large object", "parts", "retry failed parts"],
        "difficulty": "Medium",
        "exam_style_notes": "Performance and reliability scenario for large object upload behavior.",
        "distractor_pattern": "Contrast multipart upload with Transfer Acceleration, versioning, and lifecycle expiration.",
        "reasoning_pattern": "Use multipart upload so the client can upload parts in parallel and retry individual failures.",
        "generated_question": "A client application uploads multi-gigabyte files to S3 over an unreliable network and needs to retry only the failed pieces instead of restarting the whole upload. Which S3 upload method should it use?",
        "correct_option": "Use S3 multipart upload.",
        "reference_answer": "Use S3 multipart upload to split a large object into parts, upload them independently, and retry failed parts without restarting the full upload.",
        "distractors": ["Enable S3 object lock.", "Use S3 Lifecycle expiration.", "Configure CloudTrail data events only."],
    },
    {
        "source_id": "dva-kms-envelope-encryption",
        "source_name": "AWS Documentation: Envelope encryption",
        "source_url": "https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#enveloping",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Security",
        "task_statement": "Use AWS KMS to protect a data key that encrypts application data outside KMS.",
        "services": ["AWS KMS"],
        "concepts": ["KMS envelope encryption", "data key", "customer managed key", "encrypted data key"],
        "difficulty": "Medium",
        "exam_style_notes": "Application encryption scenario requiring the difference between data keys and KMS keys.",
        "distractor_pattern": "Contrast envelope encryption with Secrets Manager rotation, TLS certificates, and IAM access keys.",
        "reasoning_pattern": "Generate a data key, encrypt data locally, and store the encrypted data key with the ciphertext.",
        "generated_question": "An application needs to encrypt large payloads locally while using AWS KMS to protect the key material. Which encryption pattern should the developer implement?",
        "correct_option": "Use KMS envelope encryption.",
        "reference_answer": "Use KMS envelope encryption: generate a data key, encrypt the data locally, and store the encrypted data key protected by a customer managed key.",
        "distractors": ["Store plaintext keys in Lambda environment variables.", "Use an API Gateway Lambda authorizer.", "Enable S3 static website hosting."],
    },
    {
        "source_id": "dva-ssm-parameter-store-config",
        "source_name": "AWS Documentation: Systems Manager Parameter Store",
        "source_url": "https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Store hierarchical application configuration values centrally and retrieve them at runtime.",
        "services": ["AWS Systems Manager Parameter Store"],
        "concepts": ["Parameter Store", "hierarchical parameters", "application configuration", "runtime retrieval"],
        "difficulty": "Medium",
        "exam_style_notes": "Configuration management scenario distinguishing shared configuration from secret rotation.",
        "distractor_pattern": "Contrast Parameter Store with CloudWatch Logs, CodeBuild buildspecs, and API keys.",
        "reasoning_pattern": "Use Parameter Store for centralized configuration that applications can read by name or path.",
        "generated_question": "Several Lambda functions need to read shared non-rotating configuration values organized by application and environment path. Which AWS service should the developer use?",
        "correct_option": "Use Systems Manager Parameter Store.",
        "reference_answer": "Use AWS Systems Manager Parameter Store to keep hierarchical application configuration parameters and retrieve them at runtime.",
        "distractors": ["Use CloudWatch Logs Insights.", "Use CodeBuild reports.", "Create an SQS FIFO queue."],
    },
    {
        "source_id": "dva-cognito-user-pool-auth",
        "source_name": "AWS Documentation: Amazon Cognito user pools",
        "source_url": "https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Security",
        "task_statement": "Add user registration and authentication to an application using a managed user directory.",
        "services": ["Amazon Cognito"],
        "concepts": ["Cognito user pool", "user registration", "authentication", "managed user directory"],
        "difficulty": "Medium",
        "exam_style_notes": "Application authentication scenario asking for managed user identity rather than AWS resource permissions.",
        "distractor_pattern": "Distinguish user pools from identity pools, IAM roles, and API keys.",
        "reasoning_pattern": "Use a Cognito user pool for app-user sign-up, sign-in, and token issuance.",
        "generated_question": "A mobile application needs managed sign-up, sign-in, password recovery, and tokens for its end users. Which Cognito feature should the developer configure?",
        "correct_option": "Configure an Amazon Cognito user pool.",
        "reference_answer": "Configure an Amazon Cognito user pool to provide managed user registration, authentication, password recovery, and token issuance.",
        "distractors": ["Create an IAM group for the users.", "Use an S3 presigned URL.", "Enable DynamoDB Streams."],
    },
    {
        "source_id": "dva-codedeploy-lambda-canary",
        "source_name": "AWS Documentation: CodeDeploy deployments for Lambda",
        "source_url": "https://docs.aws.amazon.com/codedeploy/latest/userguide/tutorial-lambda.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Deployment",
        "task_statement": "Shift Lambda alias traffic gradually to a new function version and roll back on alarms.",
        "services": ["AWS CodeDeploy", "AWS Lambda"],
        "concepts": ["CodeDeploy Lambda deployment", "traffic shifting", "Lambda alias", "rollback alarms"],
        "difficulty": "Medium",
        "exam_style_notes": "Safe deployment scenario involving Lambda versions, aliases, alarms, and rollout strategy.",
        "distractor_pattern": "Contrast CodeDeploy traffic shifting with CodeBuild compilation, manual alias changes, and API throttling.",
        "reasoning_pattern": "Use CodeDeploy for Lambda deployments to shift alias traffic and trigger rollback when alarms fire.",
        "generated_question": "A team releases a new Lambda version and wants 10 percent of alias traffic to move first, with automatic rollback if CloudWatch alarms fire. Which deployment service should the developer use?",
        "correct_option": "Use CodeDeploy for Lambda traffic shifting.",
        "reference_answer": "Use AWS CodeDeploy for a Lambda deployment that shifts alias traffic gradually and rolls back when configured alarms are triggered.",
        "distractors": ["Use CodeBuild batch builds.", "Use DynamoDB transactions.", "Configure SQS long polling only."],
    },
    {
        "source_id": "dva-codebuild-report-group",
        "source_name": "AWS Documentation: CodeBuild test reports",
        "source_url": "https://docs.aws.amazon.com/codebuild/latest/userguide/test-reporting.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Deployment",
        "task_statement": "Collect and visualize unit test results produced by a CodeBuild project.",
        "services": ["AWS CodeBuild"],
        "concepts": ["CodeBuild report group", "test reports", "unit test results", "build project"],
        "difficulty": "Medium",
        "exam_style_notes": "CI feedback scenario where build output should include structured test reporting.",
        "distractor_pattern": "Distinguish report groups from buildspec commands alone, CodeDeploy hooks, and CloudWatch metrics.",
        "reasoning_pattern": "Configure report groups and buildspec report paths so CodeBuild can ingest test result files.",
        "generated_question": "A CodeBuild project runs unit tests and the team wants test case results visible in CodeBuild instead of only raw log output. What should the developer configure?",
        "correct_option": "Configure a CodeBuild report group.",
        "reference_answer": "Configure a CodeBuild report group and buildspec report file paths so CodeBuild collects and displays structured unit test results.",
        "distractors": ["Create a CodeDeploy AppSpec file.", "Enable S3 Transfer Acceleration.", "Configure API Gateway throttling."],
    },
    {
        "source_id": "dva-cloudwatch-logs-insights",
        "source_name": "AWS Documentation: CloudWatch Logs Insights",
        "source_url": "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AnalyzingLogData.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Troubleshooting and Optimization",
        "task_statement": "Query application log groups to find patterns and errors without exporting logs.",
        "services": ["Amazon CloudWatch"],
        "concepts": ["CloudWatch Logs Insights", "log query", "log groups", "error analysis"],
        "difficulty": "Medium",
        "exam_style_notes": "Troubleshooting scenario focused on querying application logs already stored in CloudWatch.",
        "distractor_pattern": "Contrast log querying with X-Ray traces, CloudTrail events, and metrics alarms.",
        "reasoning_pattern": "Use Logs Insights queries to search and aggregate log events across selected log groups.",
        "generated_question": "A Lambda application writes JSON logs to CloudWatch Logs, and a developer needs to search recent log groups for common error codes and counts. Which CloudWatch capability should be used?",
        "correct_option": "Use CloudWatch Logs Insights.",
        "reference_answer": "Use CloudWatch Logs Insights to run queries against selected log groups and analyze error patterns in application logs.",
        "distractors": ["Use AWS Config rules.", "Use an SQS dead-letter queue.", "Use CodePipeline manual approval."],
    },
    {
        "source_id": "dva-xray-annotations-filtering",
        "source_name": "AWS Documentation: AWS X-Ray annotations",
        "source_url": "https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-annotations",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Troubleshooting and Optimization",
        "task_statement": "Add indexed metadata to X-Ray traces so traces can be filtered by business identifiers.",
        "services": ["AWS X-Ray"],
        "concepts": ["X-Ray annotations", "indexed metadata", "trace filtering", "segments"],
        "difficulty": "Medium",
        "exam_style_notes": "Tracing scenario asking how to make request traces searchable by a custom key.",
        "distractor_pattern": "Distinguish annotations from metadata, CloudWatch dimensions, and log fields.",
        "reasoning_pattern": "Add X-Ray annotations to segments when values need to be indexed for filter expressions.",
        "generated_question": "A developer instruments an application with X-Ray and needs to filter traces by tenant ID in the X-Ray console. Which kind of trace data should the code add?",
        "correct_option": "Add X-Ray annotations.",
        "reference_answer": "Add X-Ray annotations to segments because annotations are indexed metadata that can be used in trace filter expressions.",
        "distractors": ["Add unindexed X-Ray metadata only.", "Create an API Gateway usage plan.", "Enable S3 multipart upload."],
    },
    {
        "source_id": "dva-eventbridge-custom-bus",
        "source_name": "AWS Documentation: Amazon EventBridge event buses",
        "source_url": "https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-bus.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Route custom application events to targets using rules on a dedicated EventBridge event bus.",
        "services": ["Amazon EventBridge"],
        "concepts": ["EventBridge custom event bus", "custom events", "rules", "targets"],
        "difficulty": "Medium",
        "exam_style_notes": "Event routing scenario for decoupled applications that publish domain events.",
        "distractor_pattern": "Contrast custom event buses with scheduled rules, SNS fanout, and direct Lambda invokes.",
        "reasoning_pattern": "Publish custom events to an event bus and use rules to match patterns and invoke targets.",
        "generated_question": "Several services publish domain events, and the platform team wants rules to route matching custom events to different Lambda targets without direct service-to-service calls. Which EventBridge resource should be used?",
        "correct_option": "Use a custom EventBridge event bus with rules.",
        "reference_answer": "Use a custom EventBridge event bus and rules to receive custom application events, match event patterns, and route them to targets.",
        "distractors": ["Use S3 Lifecycle policies.", "Use a CodeBuild report group.", "Use Lambda environment variables only."],
    },
    {
        "source_id": "dva-step-functions-error-retry",
        "source_name": "AWS Documentation: Step Functions error handling",
        "source_url": "https://docs.aws.amazon.com/step-functions/latest/dg/concepts-error-handling.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Define retries and fallback paths for failed states in a Step Functions workflow.",
        "services": ["AWS Step Functions"],
        "concepts": ["Step Functions Retry", "Catch", "state machine", "error handling"],
        "difficulty": "Medium",
        "exam_style_notes": "Workflow resilience scenario asking how to handle task failures declaratively.",
        "distractor_pattern": "Contrast state machine Retry/Catch with Lambda DLQs, SQS visibility timeout, and CloudWatch alarms.",
        "reasoning_pattern": "Add Retry and Catch fields to states so the workflow handles transient and terminal errors.",
        "generated_question": "A Step Functions workflow calls several Lambda tasks and should retry transient errors, then move to a compensating path when retries are exhausted. What should the developer define in the state machine?",
        "correct_option": "Define Step Functions Retry and Catch handlers.",
        "reference_answer": "Define Retry and Catch handlers in the Step Functions state machine to retry transient errors and transition to fallback states when failures persist.",
        "distractors": ["Configure an S3 presigned URL.", "Enable DynamoDB TTL.", "Use CodeBuild environment variables."],
    },
    {
        "source_id": "dva-lambda-layer-shared-dependencies",
        "source_name": "AWS Documentation: Lambda layers",
        "source_url": "https://docs.aws.amazon.com/lambda/latest/dg/chapter-layers.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Share common libraries across multiple Lambda functions without packaging them into every deployment bundle.",
        "services": ["AWS Lambda"],
        "concepts": ["Lambda layer", "shared libraries", "deployment package", "function dependencies"],
        "difficulty": "Medium",
        "exam_style_notes": "Packaging scenario focused on reusable dependencies for serverless functions.",
        "distractor_pattern": "Contrast layers with environment variables, aliases, and provisioned concurrency.",
        "reasoning_pattern": "Publish shared dependencies as a layer and attach the layer to functions that need them.",
        "generated_question": "Multiple Lambda functions use the same internal utility library, and the team wants to manage that library separately from each function package. Which Lambda feature should the developer use?",
        "correct_option": "Use a Lambda layer.",
        "reference_answer": "Use a Lambda layer to package shared libraries separately and attach the layer to each function that needs those dependencies.",
        "distractors": ["Use Lambda environment variables.", "Use API Gateway throttling.", "Use DynamoDB conditional writes."],
    },
    {
        "source_id": "dva-ecr-image-scanning",
        "source_name": "AWS Documentation: Amazon ECR image scanning",
        "source_url": "https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Deployment",
        "task_statement": "Scan container images in Amazon ECR for package vulnerabilities before deployment.",
        "services": ["Amazon ECR"],
        "concepts": ["ECR image scanning", "container image", "vulnerabilities", "repository"],
        "difficulty": "Medium",
        "exam_style_notes": "Container deployment security scenario asking for repository-level image assessment.",
        "distractor_pattern": "Contrast ECR scanning with CodeBuild reports, CloudTrail audit logs, and KMS encryption.",
        "reasoning_pattern": "Enable image scanning in ECR so pushed container images are checked for vulnerabilities.",
        "generated_question": "A CI pipeline pushes application container images to Amazon ECR, and security wants vulnerability findings before promotion to production. Which ECR capability should be enabled?",
        "correct_option": "Enable Amazon ECR image scanning.",
        "reference_answer": "Enable Amazon ECR image scanning on the repository so container images are scanned for known vulnerabilities before deployment.",
        "distractors": ["Enable DynamoDB point-in-time recovery.", "Configure an API Gateway Lambda authorizer.", "Create a CloudWatch dashboard only."],
    },
    {
        "source_id": "dva-artifact-iam-s3-least-privilege",
        "source_name": "AWS Documentation: IAM JSON policy elements",
        "source_url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html",
        "source_license_notes": "AWS public documentation used for topic grounding; artifact and question text are self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Security",
        "task_statement": "Review an IAM policy for least-privilege access to one application bucket prefix.",
        "services": ["AWS IAM", "Amazon S3"],
        "concepts": ["IAM policy", "least privilege", "S3 object ARN", "wildcard resource"],
        "difficulty": "Medium",
        "question_type": "artifact_review",
        "artifact_type": "iam_policy",
        "artifact_language": "json",
        "artifact_context": "The Lambda execution role should read only objects under s3://example-bucket/reports/.",
        "artifact_body": "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Action\": \"s3:GetObject\",\n      \"Resource\": \"*\"\n    }\n  ]\n}",
        "expected_issue": "The policy grants s3:GetObject on every resource instead of the required bucket prefix.",
        "exam_style_notes": "Security artifact-review scenario requiring least-privilege reasoning from a policy snippet.",
        "distractor_pattern": "Confuse action scoping, resource ARN scoping, bucket-level and object-level permissions.",
        "reasoning_pattern": "Inspect the policy Resource element and narrow object access to the required S3 ARN pattern.",
        "generated_question": "Review the IAM policy for the Lambda execution role. What is the access-control issue, and what change best matches least privilege?",
        "correct_option": "Restrict the Resource to arn:aws:s3:::example-bucket/reports/*.",
        "reference_answer": "The policy allows s3:GetObject on every resource with Resource \"*\". For least privilege, scope the permission to the required object ARN pattern, such as arn:aws:s3:::example-bucket/reports/*.",
        "distractors": ["Add s3:PutObject to the same policy statement.", "Replace the execution role with an IAM user access key.", "Move the bucket name into a Lambda environment variable."],
    },
    {
        "source_id": "dva-artifact-lambda-hardcoded-secret",
        "source_name": "AWS Documentation: Lambda environment variables and security",
        "source_url": "https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html",
        "source_license_notes": "AWS public documentation used for topic grounding; artifact and question text are self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Security",
        "task_statement": "Review Lambda code that hard-codes a database password in the function package.",
        "services": ["AWS Lambda", "AWS Secrets Manager"],
        "concepts": ["Lambda code", "hard-coded secret", "Secrets Manager", "runtime retrieval"],
        "difficulty": "Medium",
        "question_type": "artifact_review",
        "artifact_type": "lambda_code",
        "artifact_language": "python",
        "artifact_context": "The function connects to a database from a production Lambda environment.",
        "artifact_body": "import os\n\nDB_PASSWORD = \"correct-horse-battery-staple\"\n\ndef handler(event, context):\n    return connect(os.environ[\"DB_HOST\"], DB_PASSWORD).query(event[\"sql\"])",
        "expected_issue": "The function package contains a hard-coded secret instead of retrieving it from a managed secret store.",
        "exam_style_notes": "Security code-review scenario asking how to remediate unsafe Lambda secret handling.",
        "distractor_pattern": "Confuse non-secret environment variables, IAM roles alone, KMS alone, and managed secret retrieval.",
        "reasoning_pattern": "Identify the hard-coded credential and recommend managed secret storage with runtime retrieval.",
        "generated_question": "Review the Lambda handler. What security problem should the developer fix before deployment, and what AWS service is the best fit?",
        "correct_option": "Store the credential in AWS Secrets Manager and retrieve it at runtime.",
        "reference_answer": "The password is hard-coded in the Lambda deployment package. Store the credential in AWS Secrets Manager, grant the execution role permission to read it, and retrieve it at runtime instead of shipping the secret in code.",
        "distractors": ["Keep the password in the source file and encrypt the zip file manually.", "Put the password in CloudWatch Logs for auditability.", "Use provisioned concurrency to protect the password."],
    },
    {
        "source_id": "dva-artifact-sdk-pagination",
        "source_name": "AWS Documentation: AWS SDK for Python S3 examples",
        "source_url": "https://docs.aws.amazon.com/code-library/latest/ug/python_3_s3_code_examples.html",
        "source_license_notes": "Public SDK documentation used for topic grounding; artifact and question text are self-authored.",
        "allowed_use": "Public AWS SDK documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Review SDK code that assumes one list API call returns every object in an S3 bucket.",
        "services": ["Amazon S3", "AWS SDK for Python"],
        "concepts": ["SDK pagination", "S3 ListObjectsV2", "paginator", "truncated results"],
        "difficulty": "Medium",
        "question_type": "artifact_review",
        "artifact_type": "sdk_usage",
        "artifact_language": "python",
        "artifact_context": "The bucket contains more objects than a single ListObjectsV2 response can return.",
        "artifact_body": "import boto3\n\ns3 = boto3.client(\"s3\")\n\ndef all_keys(bucket):\n    response = s3.list_objects_v2(Bucket=bucket)\n    return [item[\"Key\"] for item in response.get(\"Contents\", [])]",
        "expected_issue": "The code reads only the first page of a paginated S3 response.",
        "exam_style_notes": "SDK artifact-review scenario requiring recognition of pagination behavior and incomplete result handling.",
        "distractor_pattern": "Confuse pagination with retries, region settings, credentials, and bucket policies.",
        "reasoning_pattern": "Identify that the SDK call can return truncated results and replace it with paginator iteration.",
        "generated_question": "Review the SDK helper. Why can this function miss objects, and what SDK pattern should the developer use?",
        "correct_option": "Use an S3 ListObjectsV2 paginator and iterate through every page.",
        "reference_answer": "The code calls list_objects_v2 once, so it can return only the first page when the bucket has more results. Use the SDK paginator for ListObjectsV2 and iterate over each page before collecting keys.",
        "distractors": ["Store static access keys in the source file.", "Disable S3 versioning on the bucket.", "Increase Lambda memory to force more results into one response."],
    },
    {
        "source_id": "dva-artifact-sam-missing-policy",
        "source_name": "AWS Documentation: AWS SAM policy templates",
        "source_url": "https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html",
        "source_license_notes": "AWS public documentation used for topic grounding; artifact and question text are self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Deployment",
        "task_statement": "Review a SAM template where a Lambda function reads from DynamoDB without an attached read policy.",
        "services": ["AWS SAM", "AWS Lambda", "Amazon DynamoDB"],
        "concepts": ["SAM template", "Lambda execution role", "DynamoDB read policy", "least privilege"],
        "difficulty": "Medium",
        "question_type": "artifact_review",
        "artifact_type": "sam_template",
        "artifact_language": "yaml",
        "artifact_context": "The function code calls DynamoDB GetItem on the Sessions table.",
        "artifact_body": "Resources:\n  SessionReader:\n    Type: AWS::Serverless::Function\n    Properties:\n      Handler: app.handler\n      Runtime: python3.11\n      Environment:\n        Variables:\n          TABLE_NAME: !Ref SessionsTable\n  SessionsTable:\n    Type: AWS::DynamoDB::Table\n    Properties:\n      BillingMode: PAY_PER_REQUEST\n      AttributeDefinitions:\n        - AttributeName: sessionId\n          AttributeType: S\n      KeySchema:\n        - AttributeName: sessionId\n          KeyType: HASH",
        "expected_issue": "The function has no policy granting DynamoDB read access to the table.",
        "exam_style_notes": "Deployment artifact-review scenario requiring SAM permission reasoning for a Lambda function.",
        "distractor_pattern": "Confuse environment variables, table creation, handler settings, and execution-role permissions.",
        "reasoning_pattern": "Inspect the SAM function properties and add a least-privilege policy that grants read access to the table.",
        "generated_question": "Review the SAM template. The function deploys but receives AccessDenied when it calls GetItem. What is missing from the template?",
        "correct_option": "Add a least-privilege DynamoDB read policy for the Sessions table to the function.",
        "reference_answer": "The template passes the table name but does not grant the Lambda execution role permission to read the table. Add a least-privilege SAM policy, such as DynamoDBReadPolicy scoped to SessionsTable, or an equivalent IAM policy on the function role.",
        "distractors": ["Output the table name as plaintext to fix AccessDenied.", "Change the Lambda runtime to Node.js.", "Add a CloudWatch dashboard for the table."],
    },
]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("data/original_questions/developer_associate_sources.json"))
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(SOURCE_ROWS, indent=2) + "\n", encoding="utf-8")
    print(f"Saved {len(SOURCE_ROWS)} source question metadata rows to {args.output}.")


if __name__ == "__main__":
    main()
