#!/usr/bin/env python3
"""Create permitted Developer Associate source-question metadata."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


DEVELOPER_CERTIFICATION = "AWS Certified Developer"
DEVELOPER_EXAM_CODE = "DVA-C02"


SOURCE_ROWS = [
    {
        "source_id": "dva-lambda-sqs-dlq",
        "source_name": "AWS Documentation: Lambda with SQS event sources",
        "source_url": "https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Select an event-driven processing pattern that retries failed queue messages and isolates poison messages.",
        "services": ["AWS Lambda", "Amazon SQS"],
        "concepts": ["Lambda event source mapping", "SQS queue", "dead-letter queue", "failed message retry"],
        "difficulty": "Medium",
        "exam_style_notes": "Troubleshooting scenario with an event source, retry behavior, and failure isolation distractors.",
        "distractor_pattern": "Confuse Lambda async destinations, SNS fanout, and CloudWatch alarms with queue failure handling.",
        "reasoning_pattern": "Choose the configuration that preserves messages while preventing repeated failures from blocking processing.",
    },
    {
        "source_id": "dva-api-gateway-lambda-auth",
        "source_name": "AWS Documentation: API Gateway Lambda authorizers",
        "source_url": "https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Security",
        "task_statement": "Secure an API by running custom authorization logic before a backend Lambda integration is invoked.",
        "services": ["Amazon API Gateway", "AWS Lambda"],
        "concepts": ["API Gateway", "Lambda authorizer", "custom authorization", "backend integration"],
        "difficulty": "Medium",
        "exam_style_notes": "Security configuration scenario asking for the best API access-control mechanism.",
        "distractor_pattern": "Contrast authorizers with WAF rules, security groups, and IAM roles for compute.",
        "reasoning_pattern": "Identify request-time authorization at the API boundary rather than network or instance controls.",
    },
    {
        "source_id": "dva-dynamodb-conditional-write",
        "source_name": "AWS Documentation: DynamoDB condition expressions",
        "source_url": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Prevent overwriting an item when concurrent writers try to create the same DynamoDB record.",
        "services": ["Amazon DynamoDB"],
        "concepts": ["DynamoDB", "condition expression", "conditional write", "concurrent writes"],
        "difficulty": "Medium",
        "exam_style_notes": "Data consistency scenario requiring a service feature rather than application-side locking.",
        "distractor_pattern": "Confuse conditional writes with scans, global tables, and provisioned throughput changes.",
        "reasoning_pattern": "Use an atomic write condition to enforce uniqueness at the table operation.",
    },
    {
        "source_id": "dva-codepipeline-codebuild",
        "source_name": "AWS Documentation: CodePipeline with CodeBuild",
        "source_url": "https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodeBuild.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Deployment",
        "task_statement": "Run repeatable build and test commands as part of an automated application release pipeline.",
        "services": ["AWS CodePipeline", "AWS CodeBuild"],
        "concepts": ["CodePipeline", "CodeBuild", "build stage", "automated release"],
        "difficulty": "Medium",
        "exam_style_notes": "CI/CD workflow scenario with build automation and deployment-stage distractors.",
        "distractor_pattern": "Contrast build actions with CodeDeploy traffic shifting, CloudFormation stacks, and manual scripts.",
        "reasoning_pattern": "Choose the managed build action that integrates into a deployment pipeline.",
    },
    {
        "source_id": "dva-xray-tracing",
        "source_name": "AWS Documentation: AWS X-Ray tracing",
        "source_url": "https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Troubleshooting and Optimization",
        "task_statement": "Trace requests across distributed application components to find latency and downstream errors.",
        "services": ["AWS X-Ray"],
        "concepts": ["X-Ray", "distributed tracing", "service map", "latency troubleshooting"],
        "difficulty": "Medium",
        "exam_style_notes": "Observability troubleshooting scenario asking for request-level tracing rather than metrics alone.",
        "distractor_pattern": "Distinguish tracing from CloudWatch metrics, CloudTrail audit logs, and Config history.",
        "reasoning_pattern": "Select tracing to follow a request path across services and diagnose latency.",
    },
    {
        "source_id": "dva-lambda-env-vars",
        "source_name": "AWS Documentation: Lambda environment variables",
        "source_url": "https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Configure a Lambda function with non-secret settings that can vary between deployment environments.",
        "services": ["AWS Lambda"],
        "concepts": ["Lambda environment variables", "function configuration", "deployment environment", "non-secret settings"],
        "difficulty": "Medium",
        "exam_style_notes": "Configuration scenario asking where to store runtime settings for a serverless function.",
        "distractor_pattern": "Distinguish environment variables from Secrets Manager, IAM roles, and CloudWatch Logs.",
        "reasoning_pattern": "Use function environment configuration for non-sensitive values that differ by stage.",
    },
    {
        "source_id": "dva-secrets-manager-rotation",
        "source_name": "AWS Documentation: Secrets Manager rotation",
        "source_url": "https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Security",
        "task_statement": "Store database credentials for an application and rotate them automatically on a schedule.",
        "services": ["AWS Secrets Manager"],
        "concepts": ["Secrets Manager", "secret rotation", "database credentials", "scheduled rotation"],
        "difficulty": "Medium",
        "exam_style_notes": "Security scenario requiring managed secret storage and automatic credential rotation.",
        "distractor_pattern": "Contrast secret rotation with Lambda environment variables, KMS keys alone, and Parameter Store without rotation.",
        "reasoning_pattern": "Select the managed secrets service that can invoke rotation workflows for credentials.",
    },
    {
        "source_id": "dva-sqs-visibility-timeout",
        "source_name": "AWS Documentation: SQS visibility timeout",
        "source_url": "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Prevent other consumers from immediately receiving an SQS message while one worker is still processing it.",
        "services": ["Amazon SQS"],
        "concepts": ["SQS visibility timeout", "message processing", "queue consumers", "duplicate delivery control"],
        "difficulty": "Medium",
        "exam_style_notes": "Message-processing scenario focused on queue visibility during long-running work.",
        "distractor_pattern": "Confuse visibility timeout with delay queues, retention periods, and dead-letter queues.",
        "reasoning_pattern": "Adjust the queue visibility window so in-flight messages stay hidden long enough to finish processing.",
    },
    {
        "source_id": "dva-dynamodb-streams-lambda",
        "source_name": "AWS Documentation: Lambda with DynamoDB Streams",
        "source_url": "https://docs.aws.amazon.com/lambda/latest/dg/with-ddb.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Invoke application code when items in a DynamoDB table are inserted, updated, or deleted.",
        "services": ["Amazon DynamoDB", "AWS Lambda"],
        "concepts": ["DynamoDB Streams", "Lambda event source mapping", "table item changes", "event-driven processing"],
        "difficulty": "Medium",
        "exam_style_notes": "Event-driven data scenario asking how to react to table mutations.",
        "distractor_pattern": "Distinguish DynamoDB Streams from scans, CloudTrail events, and scheduled polling.",
        "reasoning_pattern": "Enable the stream and connect it to Lambda so record changes trigger processing.",
    },
    {
        "source_id": "dva-api-gateway-throttling",
        "source_name": "AWS Documentation: API Gateway throttling",
        "source_url": "https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Security",
        "task_statement": "Limit the request rate for clients calling a public API to protect backend integrations.",
        "services": ["Amazon API Gateway"],
        "concepts": ["API Gateway throttling", "rate limits", "burst limits", "backend protection"],
        "difficulty": "Medium",
        "exam_style_notes": "API protection scenario asking for request-rate controls at the API edge.",
        "distractor_pattern": "Contrast throttling with Lambda reserved concurrency, WAF rules, and CloudWatch alarms.",
        "reasoning_pattern": "Configure throttling limits where the API receives client traffic before invoking the backend.",
    },
    {
        "source_id": "dva-codebuild-buildspec",
        "source_name": "AWS Documentation: CodeBuild buildspec reference",
        "source_url": "https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Deployment",
        "task_statement": "Define repeatable install, build, and test commands for a managed build project.",
        "services": ["AWS CodeBuild"],
        "concepts": ["CodeBuild buildspec", "build phases", "test commands", "managed build project"],
        "difficulty": "Medium",
        "exam_style_notes": "CI build configuration scenario asking where command phases should be declared.",
        "distractor_pattern": "Distinguish buildspec files from CodeDeploy AppSpec files, IAM policies, and CloudFormation parameters.",
        "reasoning_pattern": "Place repeatable build commands in the CodeBuild buildspec so the managed build can execute them.",
    },
    {
        "source_id": "dva-eventbridge-schedule-lambda",
        "source_name": "AWS Documentation: EventBridge scheduled rules",
        "source_url": "https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-run-lambda-schedule.html",
        "source_license_notes": "AWS public documentation used for topic grounding; question text is self-authored.",
        "allowed_use": "Public AWS documentation concepts summarized locally for calibration.",
        "source_type": "documentation",
        "certification": DEVELOPER_CERTIFICATION,
        "exam_code": DEVELOPER_EXAM_CODE,
        "domain": "Development with AWS Services",
        "task_statement": "Run a Lambda function on a recurring schedule without provisioning a server.",
        "services": ["Amazon EventBridge", "AWS Lambda"],
        "concepts": ["EventBridge scheduled rule", "Lambda target", "recurring schedule", "serverless automation"],
        "difficulty": "Medium",
        "exam_style_notes": "Serverless automation scenario asking how to trigger periodic work.",
        "distractor_pattern": "Contrast scheduled rules with SQS queues, CloudTrail events, and manual invocations.",
        "reasoning_pattern": "Create a schedule rule that targets the Lambda function for recurring execution.",
    },
]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("data/original_questions/developer_associate_sources.json"))
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(SOURCE_ROWS, indent=2) + "\n", encoding="utf-8")
    print(f"Saved {len(SOURCE_ROWS)} source question metadata rows to {args.output}.")


if __name__ == "__main__":
    main()
